# All S3 configurations 
configuration:
    # AWS credential configurations
    awscredentials:
        # Access key
        accesskey: Access-key
        # Secret key
        secretkey: Secret-key

    # unit for size- B, KB (Default), MB, GB
    sizeunit: KB        

    # timeunit for SinceLastModified- seconds (Default), minutes, hours, days
    timeunit: seconds

    # Bucket names <Bucket Names>, all (Default)
    buckets: !!set
        ? corpsite-blog-alt
        ? corpsite-blog-dev