# All S3 configurations. Must set Access-key and Secret-key
configuration:
    # AWS credential configurations
    awscredentials:
        # Access key
        accesskey: <Access-key>
        # Secret key
        secretkey: <Secret-key>

    # sizeunit (optional): is unit for size- B, KB (Default), MB
    sizeunit: KB        

    # timeunit (optional): is unit for SinceLastModified- seconds (Default), minutes, hours, days
    timeunit: seconds

    # buckets (optional): Bucket names to monitor- all (Default);
    buckets: !!set
        ? <bucket-name1>
        ? <bucket-name2>